export const metadata={title:"Privacy Policy | Ibrahim Akanni Ahmad",description:"How the AKODE portfolio handles contact, analytics, newsletter, advertising, AI and related data."};

export default function Privacy(){
  return <main className="page">
    <p className="eyebrow">PRIVACY POLICY · UPDATED OCTOBER 2026</p>
    <h1>Privacy Policy</h1>
    <p className="lead">This policy explains what information the AKODE portfolio may process as the site grows into a digital headquarters for projects, articles, books, tools, Aelia and newsletters.</p>
    <section className="policy-list">
      <div className="card"><h2>1. Information you provide</h2><p>Contact forms, newsletter subscriptions and other voluntary features may collect information such as your name, email address and the message or subscription details you submit. Do not send passwords, API keys, payment credentials or other secrets through public forms.</p></div>
      <div className="card"><h2>2. Site usage and analytics</h2><p>The site may process technical and usage information such as pages viewed, referrers, approximate region, device/browser information and interaction events when analytics features are enabled. Analytics will be configured to support product improvement and security rather than to collect unnecessary personal information.</p></div>
      <div className="card"><h2>3. Aelia</h2><p>Aelia may process questions you send to the AI interface so it can generate a response. The planned agent architecture will keep tool permissions separate from ordinary chat, record only the operational information needed for security and debugging, and avoid giving the model access to secrets by default.</p></div>
      <div className="card"><h2>4. Advertising</h2><p>The portfolio may display third-party advertising after the site is approved and configured with an advertising provider. Advertising providers can use cookies or similar technologies according to their own policies and applicable consent requirements. Advertising is not guaranteed to be active on every visit.</p></div>
      <div className="card"><h2>5. Cookies and similar technologies</h2><p>Necessary technologies may support security, navigation and core functionality. Analytics, advertising and other optional technologies will be treated according to the site's cookie controls and applicable law. See the Cookies Policy for more detail.</p></div>
      <div className="card"><h2>6. External links</h2><p>AKODE links to external websites, publishers, book platforms, social networks, project sites and other services. Once you leave AKODE, the destination's own privacy policy and terms apply.</p></div>
      <div className="card"><h2>7. Email and newsletter</h2><p>Newsletter and transactional email features may use an email delivery provider. Subscription records are used to deliver the service requested and to manage unsubscribes. Application email addresses will be separated from the founder's private mailbox where possible.</p></div>
      <div className="card"><h2>8. Security</h2><p>Reasonable technical and organizational safeguards will be used, including server-side secrets, access controls, validation and logging. No internet service can promise absolute security.</p></div>
      <div className="card"><h2>9. Retention</h2><p>Information is retained only for as long as it is needed for the relevant purpose, legal obligations, security, dispute handling or service operation. Retention periods may differ by feature.</p></div>
      <div className="card"><h2>10. Your choices</h2><p>Where applicable, you may unsubscribe from newsletters, adjust optional cookie preferences, or contact the site about information associated with your interaction. Requests may require enough information to verify the request without asking for unnecessary personal data.</p></div>
      <div className="card"><h2>11. Children</h2><p>The portfolio is not designed to knowingly collect unnecessary personal information from children. If you believe a child has submitted personal information that should not have been collected, contact the site so the situation can be reviewed.</p></div>
      <div className="card"><h2>12. Policy changes</h2><p>This policy may be updated as AKODE adds analytics, advertising, newsletter, database, AI-agent and other features. The updated date at the top indicates the current published version.</p></div>
    </section>
    <section className="feature"><h2>Privacy contact</h2><p>For privacy questions, use the contact page or the published support address. Please do not email passwords, API keys or payment information.</p><a className="button" href="/contact">Contact AKODE →</a></section>
  </main>;
}