export type Post = {
  slug: string;
  title: string;
  category: string;
  excerpt: string;
  date: string;
  content: string[];
  sources?: { label: string; url: string }[];
};

type Topic = Omit<Post, "content"> & {
  focus: string;
  details: string[];
};

const topics: Topic[] = [
  { slug:"building-an-independent-digital-ecosystem", title:"Building an Independent Digital Ecosystem: The Vision Behind My Work", category:"Founder", excerpt:"A long-form look at the connected ideas behind my software, AI, communication, publishing and creator projects.", date:"September 2026", focus:"the relationship between Novella Matrix, AELIA AI, SeaChat, AKODE, publishing and a founder portfolio", details:["turning separate ideas into connected products","building infrastructure instead of only landing pages","documenting what is live, planned and experimental","using each project to teach lessons for the next"] },
  { slug:"aelia-ai-from-vision-to-platform", title:"AELIA AI: From a Big Vision to a Real Platform", category:"AI", excerpt:"What it takes to turn an ambitious AI portal into a production system rather than a simple chat interface.", date:"September 2026", focus:"AELIA AI's vision for accessible intelligence, creative tools, documents, search, automation and developer capabilities", details:["secure server-side AI requests","credits, billing and API keys","files, history, analytics and account controls","staged architecture instead of trying to launch everything at once"] },
  { slug:"seachat-sovereign-communication", title:"SeaChat and the Idea of a Sovereign Communication Network", category:"Technology", excerpt:"Why communication products need more than messaging: identity, privacy, communities, creators and trust.", date:"September 2026", focus:"SeaChat's communication-network direction and its identity, messaging, community and creator layers", details:["email and phone verification","real-time messaging infrastructure","communities, moderation and verified identities","wallet, premium and creator possibilities"] },
  { slug:"novella-matrix-digital-ecosystem", title:"Novella Matrix: Connecting Technology, Creators and Digital Products", category:"Founder", excerpt:"The role of Novella Matrix as the wider home for software, publishing, advertising, SEO and product development.", date:"September 2026", focus:"Novella Matrix as an ecosystem for developers, creators, authors, advertising, SEO and digital products", details:["developer infrastructure","author discovery","SEO and advertising operations","shared services and product integrations"] },
  { slug:"akode-learn-build-scale", title:"AKODE: Learn, Build, Scale", category:"Development", excerpt:"Why a developer-focused project can be both a learning environment and a foundation for serious products.", date:"September 2026", focus:"AKODE's learn-build-scale philosophy and the practical skills behind production software", details:["Git and deployment","APIs, databases and authentication","learning from build failures","reusing engineering patterns across products"] },
  { slug:"why-long-form-content-still-matters", title:"Why Long-Form Content Still Matters for Modern Websites", category:"SEO", excerpt:"A practical explanation of how detailed content can serve readers, brands and search discovery at the same time.", date:"September 2026", focus:"long-form content as a useful information layer rather than a word-count trick", details:["answering real questions","headings and internal links","original experience and examples","building a durable content library"] },
  { slug:"technical-seo-for-product-portfolios", title:"Technical SEO for a Product Portfolio: The Foundations That Matter", category:"SEO", excerpt:"A practical framework for organizing a growing portfolio so people and search engines can understand it.", date:"September 2026", focus:"technical SEO architecture for a portfolio with many products, domains, articles and entities", details:["project hubs","internal linking","metadata and sitemaps","performance and structured content"] },
  { slug:"author-discovery-in-the-digital-age", title:"Author Discovery in the Digital Age: More Than a Book Link", category:"Authors", excerpt:"Why authors benefit from permanent discovery pages, useful context and reader-focused editorial content.", date:"September 2026", focus:"author discovery pages and book features, including the Namelesswriter example", details:["author identity","book pages","accurate supplied information","links to legitimate publication destinations"], sources:[
      {label:"Namelesswriter author feature",url:"/authors/namelesswriter"},
      {label:"Branded Omega — Pahina",url:"https://m.pahina.com/novel/2611437824.html"},
      {label:"Second novel — Pahina",url:"https://m.pahina.com/novel/3828441344.html"}
    ] },
  { slug:"building-author-campaigns-that-readers-can-use", title:"Building Author Campaigns That Readers Can Actually Use", category:"Authors", excerpt:"A reader-first approach to author promotion, discovery pages and community outreach.", date:"September 2026", focus:"reader-first author outreach and the difference between useful discovery and repetitive advertising", details:["understanding genre and audience","permanent campaign destinations","community rules","measuring meaningful engagement"], sources:[
      {label:"Featured author: Amadi Gift / Namelesswriter",url:"/authors/namelesswriter"},
      {label:"Branded Omega — Pahina",url:"https://m.pahina.com/novel/2611437824.html"},
      {label:"Second novel — Pahina",url:"https://m.pahina.com/novel/3828441344.html"}
    ] },
  { slug:"ai-tools-for-writers-and-creators", title:"AI Tools for Writers and Creators: Assistance Without Losing the Human Voice", category:"AI & Authors", excerpt:"How AI can support research, organization and creative workflows while keeping authorship and judgment human.", date:"September 2026", focus:"responsible AI assistance for authors, creators and publishing workflows", details:["research organization","editing assistance","content operations","privacy and human review"] },
  { slug:"what-building-in-lagos-teaches-a-developer", title:"What Building Digital Products in Lagos Teaches a Developer", category:"Founder", excerpt:"A founder note about building ambitious digital products while working within practical infrastructure constraints.", date:"September 2026", focus:"the practical lessons of building ambitious software from Lagos", details:["connectivity and infrastructure","cost-aware engineering","local payment realities","breaking large goals into small milestones"] },
  { slug:"from-idea-to-production", title:"From Idea to Production: The Layers Behind a Real Web Product", category:"Development", excerpt:"A practical map of the layers that turn a concept into a deployed, maintainable application.", date:"September 2026", focus:"the engineering layers between an idea and a dependable production application", details:["scope and information architecture","databases and APIs","authentication and authorization","deployment, observability and iteration"] },
  { slug:"why-a-portfolio-can-be-a-knowledge-base", title:"Why a Portfolio Can Become a Knowledge Base", category:"Web", excerpt:"The case for turning a personal portfolio into a structured library of projects, experiments and lessons.", date:"September 2026", focus:"turning a personal website into a durable public knowledge library", details:["project hubs","technical case studies","timelines and documentation","serving different audiences from one site"] },
  { slug:"designing-a-multi-project-digital-identity", title:"Designing a Multi-Project Digital Identity Without Losing Clarity", category:"Brand", excerpt:"How one founder can present many products without making the portfolio feel like a random collection of links.", date:"September 2026", focus:"brand and information architecture for a founder with many products and deployments", details:["hierarchy","project-specific identities","progressive disclosure","clear primary and alternate links"] },
  { slug:"the-role-of-analytics-in-product-building", title:"The Role of Analytics in Product Building", category:"Product", excerpt:"Why analytics should answer product questions rather than become a dashboard of numbers.", date:"September 2026", focus:"using analytics to learn what visitors and users actually need", details:["questions before metrics","engagement context","privacy","turning measurement into product decisions"] },
  { slug:"building-trust-into-digital-products", title:"Building Trust Into Digital Products", category:"Technology", excerpt:"Identity, transparency, security and honest product status are foundations for sustainable digital services.", date:"September 2026", focus:"trust as a product feature built from security, transparency, identity and reliable behavior", details:["secret management","accurate project status","author information","error handling and support"] },
  { slug:"the-future-of-personal-websites", title:"The Future of Personal Websites: From Résumé to Digital Headquarters", category:"Web", excerpt:"Why a modern personal website can become an interactive headquarters for projects, writing, tools and identity.", date:"September 2026", focus:"the evolution of personal websites into interactive digital headquarters", details:["project archives","long-form writing","interactive tools","connecting multiple domains"] },
  { slug:"building-a-publishing-layer-for-authors", title:"Building a Publishing Layer for Independent Authors", category:"Publishing", excerpt:"A concept for connecting authors, books, discovery content and legitimate publication destinations.", date:"September 2026", focus:"software infrastructure that can help independent authors organize discovery and publishing information", details:["author profiles","book records","genre discovery","campaign and analytics workflows"], sources:[
      {label:"Namelesswriter author feature",url:"/authors/namelesswriter"},
      {label:"Branded Omega — Pahina",url:"https://m.pahina.com/novel/2611437824.html"},
      {label:"Second novel — Pahina",url:"https://m.pahina.com/novel/3828441344.html"}
    ] },
  { slug:"lessons-from-building-many-projects", title:"Lessons From Building Many Projects at Once", category:"Founder", excerpt:"What multiple projects teach about scope, reuse, documentation and deciding what to build next.", date:"September 2026", focus:"the lessons that emerge when one founder develops several connected products", details:["scope control","reusable engineering patterns","documentation","prioritization and deployment discipline"] },
  { slug:"web-development-in-the-ai-era", title:"Web Development in the AI Era: What Still Requires Engineering", category:"Technology", excerpt:"AI can generate code quickly, but production software still needs architecture, testing, security and product judgment.", date:"September 2026", focus:"the engineering work that remains essential when AI accelerates coding", details:["verification","architecture","security","testing and human product judgment"] },
  { slug:"creating-a-digital-home-for-books-and-software", title:"Creating a Digital Home for Books and Software at the Same Time", category:"Publishing", excerpt:"Why technology and storytelling can share one portfolio when the information architecture is designed carefully.", date:"September 2026", focus:"combining software projects and publishing work in one coherent portfolio", details:["separate hubs","crossover articles","entity relationships","quality over filler"] },
  { slug:"ai-and-seo-news-september-2026", title:"AI, Search and SEO News in September 2026: What Website Builders Should Watch", category:"News & SEO", excerpt:"A dated review of recent AI, search and publisher developments and what they mean for people building websites.", date:"September 20, 2026", focus:"recent developments around AI transparency, AI crawling controls and search visibility", details:["OpenAI's new AI-misbehavior disclosure framework","Cloudflare's controls for AI training and crawling","the growing overlap between search and AI systems","why publishers should understand where their content travels"], sources:[
      {label:"Reuters — OpenAI AI-misbehavior disclosure framework",url:"https://www.reuters.com/technology/openai-releases-framework-track-model-misalignment-2026-09-16/"},
      {label:"Cloudflare — controls for search and AI training",url:"https://www.cloudflare.net/news/news-details/2026/Cloudflare-Helps-End-the-Search-or-AI-Training-Tradeoff/default.aspx"},
      {label:"The SEO Wire — September 2026 search and SEO coverage",url:"https://www.theseowire.com/"}
    ] }

  { slug:"us-china-ai-safety-dialogue-september-21-2026", title:"Today in AI: US-China Talks Put AI Incident Reporting on the Agenda", category:"News & AI", excerpt:"A September 21, 2026 briefing on reported US-China discussions about AI safety, incident notification and a new dialogue mechanism.", date:"September 21, 2026", focus:"today's reported discussions between U.S. and Chinese officials about AI safety, incident notification and a new dialogue mechanism", details:["AI incident reporting","cross-border communication","frontier AI governance","what builders should learn from the news"], sources:[{label:"Associated Press — US-China AI safety discussions",url:"https://apnews.com/article/d08e58524de21511dcaba51f43faad95"},{label:"Financial Times — US-China AI dialogue",url:"https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32"}] },
  { slug:"humanoid-robotics-commercialization-news-september-21-2026", title:"Today in Technology: Humanoid Robotics Meets a Commercialization Reality Check", category:"News & Technology", excerpt:"What today's reporting about China's humanoid-robot IPO pipeline says about the difference between technical excitement and proven commercial demand.", date:"September 21, 2026", focus:"today's reporting on scrutiny of humanoid robotics valuations, IPO applications and evidence of real commercial demand", details:["robotics commercialization","valuation discipline","real-world deployment","lessons for technology builders"], sources:[{label:"Reuters — China slows humanoid robot IPO rush",url:"https://www.reuters.com/business/finance/china-slows-humanoid-robot-ipo-rush-hype-outruns-reality-2026-09-21/"}] },
  { slug:"seo-ai-search-news-september-21-2026", title:"Today in SEO: Search Is Quiet, AI Discovery Is Not", category:"News & SEO", excerpt:"A September 21, 2026 SEO briefing on confirmed Google update status, AI search visibility and why crawlability still matters.", date:"September 21, 2026", focus:"today's search status, AI-driven discovery and the technical foundations needed for pages to remain discoverable", details:["confirmed Google update status","AI search visibility","crawlability","first-party search measurement"], sources:[{label:"Google Search Status Dashboard — ranking history",url:"https://status.search.google.com/products/rGHU1u87FJnkP6W2GwMi/history"},{label:"Keywords Everywhere — current SEO news",url:"https://keywordseverywhere.com/news/"},{label:"OpenAI — crawler guidance",url:"https://help.openai.com/en/articles/20001243-advertiser-guidance-for-allowing-openai-web-crawlers"}] },
  { slug:"javascript-typescript-css-and-html-in-my-stack", title:"The Languages Behind My Work: TypeScript, JavaScript, CSS, HTML and JSON", category:"Development", excerpt:"A practical tour of the languages and formats that currently appear most often in my web-building workflow, and what each contributes.", date:"September 21, 2026", focus:"the current web stack used across this portfolio and the connected product-building workflow", details:["TypeScript and TSX","JavaScript","CSS","HTML and JSON"] },
  { slug:"why-typescript-matters-in-modern-web-products", title:"Why TypeScript Matters When a Project Starts Getting Big", category:"Development", excerpt:"Why typed JavaScript becomes increasingly useful as pages, APIs, data models and applications grow.", date:"September 21, 2026", focus:"TypeScript as a foundation for larger Next.js and Node.js applications", details:["types and contracts","safer refactoring","editor feedback","maintainable APIs"] },
  { slug:"what-javascript-does-beyond-the-interface", title:"JavaScript Beyond Buttons: The Language Connecting the Web Experience", category:"Development", excerpt:"How JavaScript powers interactions, browser behavior and server-side application logic in modern web products.", date:"September 21, 2026", focus:"JavaScript's role across browsers, React interfaces and server-side application code", details:["browser interactions","React components","server logic","API integration"] },
];

const baseParagraphs = [
  "The first principle is to start with the user rather than the technology. A project can have an impressive technical stack and still fail to communicate its purpose. Clear language, predictable navigation and a useful first action reduce the distance between a visitor and the value of the product. For a growing ecosystem, this means every major page needs a reason to exist. A project page should explain a project, an article should answer a question, an author page should introduce an author and a contact page should make communication straightforward.",
  "The second principle is architecture. As a website grows, the number of relationships grows with it. Projects connect to articles, authors connect to books, products connect to domains and technical decisions connect to future features. A structured content model makes those relationships easier to maintain. Instead of treating every page as an isolated document, the site can treat information as reusable entities. That approach is especially valuable when a founder is working on several products at the same time.",
  "The third principle is accuracy. Ambition is useful, but a portfolio should distinguish between what exists, what is being developed and what is only a future direction. This matters for technology projects and for publishing content. If a feature is planned, it can be labeled planned. If a deployment is an experiment, it can be labeled accordingly. If an author has not supplied a social profile or official synopsis, the page should not invent one. Accuracy is a long-term asset.",
  "The fourth principle is security. Public source code should not contain private API credentials. Application secrets belong in protected environment variables or a suitable secret-management system. Authentication and authorization need explicit design. Forms need validation. External integrations need controlled access. As the portfolio grows into real products, security becomes part of the product experience rather than a final checklist.",
  "The fifth principle is verification. Modern development can move quickly, especially with AI-assisted coding, but speed makes testing more important rather than less important. A production build can reveal syntax errors that are easy to miss in a long file. Browser checks can reveal broken navigation. Runtime logs can reveal failures that only appear with real requests. A dependable workflow is therefore build, inspect, fix, redeploy and verify.",
  "The sixth principle is content depth. Long articles are useful when they explain something that deserves detail. They can document a project decision, teach a technical concept, introduce an author or analyze a current development. The objective is not to add words merely to reach a target. A long page should earn its length by giving the reader more context, examples, decisions and practical takeaways.",
  "The seventh principle is internal connection. A large portfolio should not force every visitor to return to the homepage before finding the next relevant thing. Articles can link to projects. Project pages can link to articles. Author features can link to books. A central directory can link to external sites. This creates a natural path through the ecosystem and gives every page a useful next step.",
  "The final principle is iteration. A portfolio this large cannot be considered finished after one deployment. New projects will appear, old deployments will change, articles will need updates and product status will evolve. The correct goal is therefore not a permanent final version. It is a maintainable system that can keep growing without losing clarity."
];

function buildContent(topic: Topic): string[] {
  const intro = `${topic.title} sits inside a wider body of work focused on ${topic.focus}. The subject matters because modern digital products are rarely isolated. They are surrounded by content, identity, infrastructure, communities, distribution channels and decisions about what should be built next. This article records the thinking behind that direction and treats the project as work in progress rather than a claim that every ambitious feature is already complete.`;
  const unique = [
    `A useful way to understand this subject is through four practical areas: ${topic.details[0]}, ${topic.details[1]}, ${topic.details[2]} and ${topic.details[3]}. Each area looks simple when described in isolation, but the real engineering and editorial challenge appears when they have to work together. That is why the portfolio is being organized as a connected system instead of a collection of disconnected pages.`,
    `The first area, ${topic.details[0]}, affects the foundation of the experience. Users need a clear reason to arrive, a clear way to understand the product and a clear next action. For a founder portfolio this can mean discovering a project; for an AI product it can mean completing a useful task; for an author platform it can mean understanding a book and reaching its legitimate publication destination. The interface should make that path obvious without hiding important context.`,
    `The second area, ${topic.details[1]}, is where product decisions become technical decisions. Data structures, APIs, permissions, content models and deployment workflows have to support the experience. A feature that looks small in a mock-up can require several backend components in production. Thinking about those dependencies early helps avoid building a surface that cannot be supported reliably later.`,
    `The third area, ${topic.details[2]}, is where quality becomes visible. A product can be technically functional while still being difficult to understand, difficult to trust or difficult to discover. Documentation, metadata, internal links, verification, analytics and useful content all contribute to the experience. The goal is to make the system understandable to a visitor who knows nothing about the project before they arrive.`,
    `The fourth area, ${topic.details[3]}, points toward the future. Good systems should leave room for additional features without forcing every future requirement into the first release. This is particularly important for large ecosystem ideas. A staged roadmap can keep the first version focused while preserving an architecture that can grow into the larger vision.`
  ];
  return [intro, ...unique, ...baseParagraphs];
}

export const posts: Post[] = topics.map((topic) => ({
  ...topic,
  content: buildContent(topic)
}));

export const postMap = Object.fromEntries(posts.map((post) => [post.slug, post])) as Record<string, Post>;
